---
- name: Stop EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instance_id: "i-xxxx"

  tasks:
    - name: Stop EC2 instance
      ec2:
        instance_ids: "{{ instance_id }}"
        state: stopped
        region: "ap-southeast-2"
      register: ec2_info

    - name: Output stopped instance information
      debug:
        var: ec2_info

